name: lucid_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - scipy
  - pillow
  - tensorflow
  - matplotlib
  - scikit-learn
  - pip:
    - pyopengl
    - git+https://github.com/4QuantOSS/lucid
